name=GBALib_ShiftRegister
version=1.0.0
author=Graziano Blasilli
maintainer=Graziano Blasilli <graziano.blasilli@uniroma1.it>
sentence=Shift Register 74HC595N Management Library.
paragraph=This library provides a simple interface to control a 74HC595N shift register.
category=Signal Input/Output
url=https://github.com/blasilli/GBALib_ShiftRegister
architectures=*